import HomePage from '@/components/Home/HomePage'
import { useRoute } from '@/hooks/useRoute'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect } from 'react'

export default function Home() {
  const router = useRouter()
  useEffect(() => {
    const isAuth = localStorage.getItem('isAuth');
    if (isAuth !== 'true') router.push('/auth')
  }, [])
  return (
    <>
      <Head>
        <title>Регулярные пассажирские перевозки</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <HomePage />
    </>
  )
}